### ISSUE TITLE
package.json main property is wrong

### ISSUE THREAD

**Issue by AoDev** [monospaced/hamster.js#10]
Hello, 

Currently main entry has the value "elastic". It should be hamster.js . It is not possible to require this module without this. (as commonjs / npm module)

**Comment by mikepombal** [comment]
+1
Having the same problem

**Comment by hccampos** [comment]
#11

**Comment by monospaced** [comment]
fixed in #11

**Comment by monospaced** [comment]
@AoDev @mikepombal Do I need to publish this on npm as v1.1.2 now, or is it ok as is?

**Comment by AoDev** [comment]
You should bump the version and publish it.

**Comment by monospaced** [comment]
Thanks, done.

**Comment by AoDev** [comment]
Thank you :)
