### ISSUE TITLE
no destroy ?

### ISSUE THREAD

**Issue by stephanedemotte** [monospaced/hamster.js#14]
Hi,

Thanks a lot for this package.

Can you provide a destroy function ?

I try with unwheel, but i thinks it's not enough

Thanks !

**Comment by monospaced** [comment]
unwheel removes the event listeners

**Comment by zdenekhatak** [comment]
@monospaced hi, could you give me a hint how exactly call the unwheel method?

I am trying Hamster(element).unwheel() but with no success... 

Thanks in advance.

**Comment by toinelin** [comment]
Hi, got the same error here, ```Cannot read property 'normalised'``` of undefined. Cant use your lib because of this :(

**Comment by monospaced** [comment]
@toinelin https://github.com/monospaced/hamster.js/issues/18#issuecomment-367839745
