### ISSUE TITLE
unwheel method throw an error

### ISSUE THREAD

**Issue by Hiswe** [monospaced/hamster.js#18]
```js
const onWheel   = (e, delta, deltaX, deltaY) => {}
const { body }  = document
Hamster( body ).wheel( onWheel )
Hamster( body ).unwheel( onWheel )
```

throw an error 
```
TypeError: undefined is not an object (evaluating 'handlers.normalised')
remove — hamster.js:153
offEvent — hamster.js:87
```

same is in #14 

with navigators : 

- Chrome 60.0.3112.101
- Safari 10.1.1 (12603.2.4)
- Firefox 54.0.1

**Comment by monospaced** [comment]
This is poorly documented, but that’s not the API — you need to be calling `unwheel` on the same instance of `Hamster` you called `wheel` on.

In the example above, you’re creating two instance of `Hamster`, calling `wheel` on one, and `unwheel` on the other, which won’t work.

This is the correct approach:

```js
const onWheel   = (e, delta, deltaX, deltaY) => {}
const { body }  = document
const hamster = Hamster( body );

hamster.wheel( onWheel )
hamster.unwheel()
```

**Comment by monospaced** [comment]
Updated the [README](https://github.com/monospaced/hamster.js#usage)
