### ISSUE TITLE
chrome 46.0.2490.71 bug with apple touch devices

### ISSUE THREAD

**Issue by akalman** [monospaced/hamster.js#6]
the latest version of chrome has added an extra scroll event to these devices that causes the scroll wheel callback to give NaN for delta, deltaX deltaY.

**Comment by rutgervd** [comment]
I also came across this bug. Not only this, but the scroll 'inertia smoothing' now feels very different, throwing a lot of (delta: 1, deltaX: 0: deltaY1) events at the end.

**Comment by kfei** [comment]
I also came across this bug.

Possibly caused by https://codereview.chromium.org/1299643004
